export const dataMock = [
  {
    id: 1,
    name: "John Doe",
    last_name: "Doe",
    email: "email@email.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 2,
    name: "Jane Doe",
    last_name: "Doe",
    email: "jane.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 3,
    name: "Jim Doe",
    last_name: "Doe",
    email: "jim.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 4,
    name: "Jill Doe",
    last_name: "Doe",
    email: "jill.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 5,
    name: "Jack Doe",
    last_name: "Doe",
    email: "jack.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 6,
    name: "John Doe",
    last_name: "Doe",
    email: "email@email.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 7,
    name: "Jane Doe",
    last_name: "Doe",
    email: "jane.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 8,
    name: "Jim Doe",
    last_name: "Doe",
    email: "jim.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 9,
    name: "Jill Doe",
    last_name: "Doe",
    email: "jill.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 10,
    name: "Jack Doe",
    last_name: "Doe",
    email: "jack.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 11,
    name: "John Doe",
    last_name: "Doe",
    email: "email@email.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 12,
    name: "Jane Doe",
    last_name: "Doe",
    email: "jane.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 13,
    name: "Jim Doe",
    last_name: "Doe",
    email: "jim.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 14,
    name: "Jill Doe",
    last_name: "Doe",
    email: "jill.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 15,
    name: "Jack Doe",
    last_name: "Doe",
    email: "jack.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 16,
    name: "John Doe",
    last_name: "Doe",
    email: "email@email.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 17,
    name: "Jane Doe",
    last_name: "Doe",
    email: "jane.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 18,
    name: "Jim Doe",
    last_name: "Doe",
    email: "jim.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 19,
    name: "Jill Doe",
    last_name: "Doe",
    email: "jill.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
  {
    id: 20,
    name: "Jack Doe",
    last_name: "Doe",
    email: "jack.doe@example.com",
    email_confirmed: "confirmed",
    phone: "1234567890",
    first_login: "Yes",
    created_at: "2021-01-01",
    profile: "Admin",
    state: "Active",
  },
];
